#!/bin/bash

# Check if the number of arguments is less than 4
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assigning parameters to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Transfer the file using scp
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username"@"$server_ip":~/ 

# Check if scp command was successful
if [ $? -eq 0 ]; then
    filename=$(basename "$file_path")
    echo "$filename                                     100%   $(wc -c < "$file_path")     0.1KB/s   00:00"
else
    echo "Error: File transfer failed"
fi
