#!/usr/bin/env bash
#config nginx

sudo apt update
sudo apt install nginx -y
sudo touch /var/www/html/index.html

echo "Holberton" | sudo tee /var/www/html/index.html

echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/youtube.com/watch?v=QH2-TGUlwu4\/besthor permanent;"

sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

echo "add_header X-Served-By $HOSTNAME;" | sudo tee -a /etc/nginx/sites-enabled/default

sudo nginx -t
sudo service nginx restart
