#!/usr/bin/env bash
# A script that configures a HAProxy Load Balancer

# Check if the script is run with sudo
if [ "$EUID" -ne 0 ]; then
    echo "Please run this script with sudo."
    exit 1
fi

# Update package lists
apt-get update

# Install HAProxy
apt-get install -y haproxy

# Configure HAProxy
cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
EOF

# Enable HAProxy to be managed via an init script
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy service
service haproxy restart

echo "HAProxy installed and configured successfully."
