#!/usre/bin/env bash
# TCP and UDP


1. TCP is a protocol that is transferring data in a slow way but surely.
2. UDP is a protocol that is transferring data in a fast way and might loss data along in the process.
1. Have you received boxes x, y, z?
