#!/usr/bin/env bash
# A Script that configures an nginx server to listen on port 80

# Check if the script is run with sudo
if [ "$EUID" -ne 0 ]; then
    echo "Please run this script with sudo."
    exit 1
fi

# Install Nginx
apt-get update
apt-get install -y nginx

# Check if Nginx service is running, start if not
if ! systemctl is-active --quiet nginx; then
    systemctl start nginx
fi

# Check if Nginx is listening on port 80, configure if not
if ! netstat -tuln | grep -q ":80 "; then
    sed -i 's/listen\ 80;/listen\ 80\ default_server;/g' /etc/nginx/sites-available/default
    systemctl restart nginx
fi

# Create HTML content file
cat <<EOF > /var/www/html/index.html
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
EOF

# Ensure proper permissions for index.html
chown www-data:www-data /var/www/html/index.html
chmod 644 /var/www/html/index.html

# Restart Nginx to apply changes
systemctl restart nginx
