#!/usr/bin/env bash
# Ash script that dispalys till infinity and o SIGTERM signal


terminate(){
	echo "I am invicinble!!!"
	exit 0
}
trap terminate SIGTERM

counter=0
while true; do
	echo "To infinity and beyond"
	sleep 2

	((counter++))

	if [ "$counter" -eq 3 ]; then
		echo "I am invincible!!!"
		counter=0
	fi
done
