#!/usr/bin/env bash
# a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS


filename="/etc/passwd"
IFS=":"
while read -r username x uid gid comment home shell; do
	echo "The user $username is part of the $gid gang, lives in $home and rides $shell."
	echo "$uid's place is protected by the passcode $x, more info about the user here: $comment"
done < "$filename"
