#!/usr/bin/env bash
# A script that displays "Best School" and "Hi" on line 9


count=1
while [ $count -le 10 ]; do
	if [ $count -eq 9 ]; then
		echo -e "Best School\nHi"
	else
		echo "Best School"
	fi
	((count++))
done
