#!/usr/bin/env bash
# A script that displays hours and minutes


hour=0
minutes=1
while [ $hour -le 12 ]; do

	echo "Hour: $hour"

	while [ $minutes -lt 60 ]; do
		echo "$minutes"
		((minutes++))
	done
	minutes=1
	((hour++))
done
