#!/usr/bin/env bash
# Check if the script is run with root privileges


if [ "$(id -u)" -ne 0 ]; then
    exit 1
fi

# Set localhost to resolve to 127.0.0.2
echo "127.0.0.2 localhost" >> /etc/hosts

# Set facebook.com to resolve to 8.8.8.8
echo "8.8.8.8 facebook.com" >> /etc/hosts
