#!/usr/bin/env bash
# Check if the script is run with root privileges


if [ "$(id -u)" -ne 0 ]; then
    exit 1
fi

# Use ip command to display all active IPv4 IPs
ip -4 address show | grep inet | awk '{print $2}' | cut -d'/' -f1
