#!/usr/bin/env bash
# Check if the script is run with root privileges


if [ "$(id -u)" -ne 0 ]; then
    exit 1
fi

# Define the port to listen on
PORT=98

# Listen on the specified port
# Listen on the specified port
while true; do
    { echo -ne "HTTP/1.1 200 OK\r\nContent-Length: $(echo -n "Hello world\ntest" | wc -c)\r\n\r\nHello world\ntest"; } | nc -l -p $PORT -q 1
done
