#!/usr/bin/env bash

# Define the server address
server_address="100.25.181.28"

# Use ssh with the private key to connect to the server
ssh -i ~/.ssh/school ubuntu@$server_address

# Optional: Print a message upon exiting the SSH session
echo "Connection to $server_address closed."
